### ISSUE TITLE
Minor, scroll bar matches color of background

### ISSUE THREAD

**Issue by alpiepho** [talkpython/installing-python#1]
On Chrome, the background color is same/near the color of the scrollbar.  Minor thing, but I have a habit of using it to judge how far thru an article I have read.

This was a great summary for installing Python.  I would love to see a similar article for the various virtual environments.  I really like coding in Python, but I get tripped up on the setup every time.

Love the podcast(s) too.
Thanks,
Al

**Comment by mikeckennedy** [comment]
Hi @alpiepho Thanks, glad you're enjoying the how-to and the podcast. But we can't change the scrollbar. Or more specifically, we are not using CSS or other settings to control the scrollbar so whatever you're seeing is just from your browser's default setting. The page background is standard white so I would guess it is like much of the other web so I don't want to change that.
